name: Wrench
version: 1.0.2-DEVELOPMENT-SNAPSHOT
main: com.gmail.gogobebe2.wrench.Main
description: Creates a wrench that can break mob spawners.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
commands:
  wrench:
    aliases: [getwrench]